name: flutter_timeago_pro_example
description: Example app for flutter_timeago_pro package.
publish_to: 'none'
version: 1.1.2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_timeago_pro:
    path: ../
