name: flutter_timeago_pro
description: >
  A Flutter/Dart extension that formats DateTime into human-friendly timestamps,
  adapting intelligently from "Just now" to weekday or full date
  depending on how far in the past or future the time is.
version: 3.0.1
homepage: https://github.com/aslamambiloly/flutter_timeago_pro
issue_tracker: https://github.com/aslamambiloly/flutter_timeago_pro/issues
screenshots:
  - description: 'Sample formatted time used in a real world scenario'
    path: doc/cover.png

topics:
  - datetime
  - formatting
  - localization
  - utilities
  - text
  
environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
