name: flutter_timeago_pro
description: >
  A Flutter/Dart extension that formats DateTime into human-friendly
  adapting intelligently from "Just now" to weekday or full date
  depending on how far in the past the time is.
version: 1.0.4
homepage: https://github.com/aslamambiloly/flutter_timeago_pro

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
